# This is a basic workflow to help you get started with Actions

name: My-Github-Basic-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

jobs:
  my_step1:
    runs-on: ubuntu-latest
  my_testing-2:
