# This is a basic workflow to help you get started with Actions

name: My-Github-Basic-test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  - push
  - pull_request

jobs:
  my_step1:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
    
    - name: Execure few commands
      run : ansible --version

    - name: Git clone my repo
      uses: actions/checkout@v2   
  
    - name: List current folder
      run : ls -la

    - name: Ansible linter
      uses: ansible/ansible-lint-action@master
      with:
        # [required]
        # Paths to ansible files (i.e., playbooks, tasks, handlers etc..)
        # or valid Ansible directories according to the Ansible role
        # directory structure.
        # If you want to lint multiple ansible files, use the following syntax
        # targets: |
        #   playbook_1.yml
        #   playbook_2.yml
        targets: |
          terransible/course_scripts/wordpress.yml
        # [optional]
        # Arguments to override a package and its version to be set explicitly.
        # Must follow the example syntax.
        override-deps: |
          ansible==2.9
          ansible-lint
